# springboot-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-kkh
  namespace: group1-team7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-kkh
  template:
    metadata:
      labels:
        app: gateway-kkh
    spec:
      containers:
      - name: gateway-kkh
        image: k8s-vga-worker1:5000/team7-gateway-kkh:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-kkh
  namespace: group1-team7
spec:
  selector:
    app: gateway-kkh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30744
  type: NodePort